version: '2'
services:
  stukalo:
    image: ubuntu/rdp:18
    container_name: stukalo
    hostname: stukalo
    restart: always
    shm_size: 2g
    environment:
       userName: stukalo
       PASSWORDHASH: $$1$$z53Cg/fV$$06o379IvIOxj/ESruVKrG1
       IDLETIME: 11
    ports:
      - "8006:3389"
      - "2222:22"
    volumes:
      - /data/stukalo/rdp-data/ssh:/etc/ssh/
      - /data/stukalo/rdp-data/home/:/home/
